/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package blackjack

fun main() {
    var deck = Deck()
    deck.Print()
    deck.Shuffle()
    print("\n\n")
    deck.Print()
}
