/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package blackjack

fun main() {
    var deck = Deck()
    deck.Print()
	var card = deck.DrawCard()
    print("\n\nCard drawn: ${card.PrintableFormat()}\n\n")
    deck.Print()
}
